name = input("What is your name?" + " ")
age = input("What is your age?" + " ")
height = input("What is your height?" + " ")
print ("My name is" + " " + name + "," + " " + "I am", age, "years old" + " " + "with a height of", height)
print (type(name))
print (name.upper())
