# Check if the random number generated by the system matches with the user's guessed number

import random
random_number = random.randint(0,10)
guess = -1

while guess != random_number:
    userGuess = int(input("Guess the number I have in my mind between 1 and 10: "))
    if random_number == userGuess:
        print("Bro!, it matched correctly ")
        break
    else:
        print("Try again")